guerzon/vaultwarden

Chart.yaml, README.md, templates/statefulset.yaml, values.yaml
I need to run my backup and restore containers inside the vaultwarden pod and it would be nice to have support in the helm chart for this.
=> Init and sidecar containers

Chart.yaml, README.md, templates/configmap.yaml, values.yaml
I'm using Vaultwarden in my private homelab and I don't want new users to register in my instance. All users on my instance are created from the admin page. Vaultwarden supports this setup by setting the environment variables `signupsAllowed` and `invitationsAllowed` to false, so I've added them to the Helm chart as well.
=> Added parameters signupsAllowed and invitationsAllowed

templates/ingress.yaml
When using `ingressClass` for example `traefik` along with `cert-manager` it is impossible to generate certificate.
Allowing setting up `secretName` for any type of `ingressClass` fixes it.
=> fix: Allow specyfing tlsSecret not only for nginx

.github/workflows/release.yml, cr.yaml
This workflow will create an index.yaml and push it to the gh-pages branch. 
A tag will be created and the chart itself will be uploaded automatically to the GitHub releases page.
The version of the chart needs to be bumped when changes are made, otherwise the action will fail.
Closes #30
=> Add release workflow

charts/vaultwarden/templates/_helpers.tpl
This fixes issue #33 by removing the `image.tag` from the labels in the stateful set.
=> Fix labels to enable upgrading by changing the image tag

charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/values.yaml
Allow unset signup domains
Some options:
INVITATION_ORG_NAME
ICON_BLACKLIST_NON_GLOBAL_IPS
IP_HEADER
See description in Admin Panel -> Settings
=> Allow Signup domains not to be set

charts/vaultwarden/templates/statefulset.yaml, charts/vaultwarden/values.yaml
=> fix PVC: instead using storageClass with name 'default' use default storageClass

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_pvcSpec.tpl, charts/vaultwarden/values.yaml
Improved PVC configuration to optionally keep the volume after uninstalling the deployment.
The new option `keepPvc: true` will make sure that the PVC will not be deleted when a chart deployment gets uninstalled and can be resused after a new deployment.
=> Improved PVC configuration

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/values.yaml
If possbile a pod / container should never run with root privileges.
Beside securityContext the podSecurityContext was added as configuration option.
Additionally (working) example values are added for these 2 sections.
Limitation: This does only work for a new vaultwarden setup. If you upgrade from a previous chart version, you need to adapt permissions on the storage volume.
=> Improved security configuration

charts/vaultwarden/Chart.yaml, charts/vaultwarden/values.yaml
The default initialDelaySeconds for the liveness and startup probes are too high for how quickly vaultwarden boots. I have therefore reduced them to 5 seconds.
=> Reduce the initialDelaySeconds values

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/values.yaml
With the latest vaultwarden version [1.30.2](https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.2) it is possible to enable experimental client features using flags.
This comma separated list may be altered to enable additional features or disable features that are enabled by default.
The default value of `null` makes sure to use the default list of features included in the vaultwarden binary as this list might change with each release.
=> Allow configuring experimental client feature flags

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/ingress.yaml, charts/vaultwarden/values.yaml, generate-readme.sh
This pull request allows users to easily create ingress rules to allow their Vaultwarden instance to use multiple FQDNs.
Key changes:
- Updated documentation using the provided `generate-readme.sh` (btw, thank you for that!)
- In the Ingress template, add two variables for abstraction of the global scope:
- `$websocket`, which aliases back to `.Values.websocket`
- `$fullname`, which aliases back to `.Release.fullname`
- Implementation of a range around `.Values.ingress.additionalHostnames` to create:
- Ingress host records
- Ingress rule sets
- On the `generate-readme.sh` script, add a flag to use a container in privileged mode, as Podman requires that for accessing the local filesystem using the volume mount method provided.
=> feat: allow multiple ingress hostnames

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/_pvcSpec.tpl
Every time I upgrade this helm chart I got this error
```
Error: UPGRADE FAILED: cannot patch "vaultwarden" with kind StatefulSet: StatefulSet.apps "vaultwarden" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```
Lets not put all the labels from helper, because they contain also chart version which changes on every upgrade
```
volumeClaimTemplates:                                                                                            
- metadata:                                         
name: vaultwarden-data                          
labels:                                         
-             helm.sh/chart: …
```
=> Do not udpate forbidden fields for statefulset

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/_pvcSpec.tpl
This commit changes the way the `app.kubernetes.io/name` and `app.kubernetes.io/instance` labels are generated in the vaultwarden Helm chart. Previously, the `.Values` object was used directly within the template expression, which is not allowed by Helm. This change updates the expression to use the `$` symbol, which correctly references the current values context.
=> Fix app.kubernetes.io labels to use $ instead of . in vaultwarden chart

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/values.yaml
Certain setups seem to have trouble with the default ndots:5 dns config. Setting this value to 1 should resolve this.
For an example, this breaks DNS resolution of the identity.bitwarden.com domain, because it appends the Kubernetes search domain to it.
=> Fix for external DNS resolution

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/templates/ingress.yaml, charts/vaultwarden/templates/service.yaml, charts/vaultwarden/values.yaml
fixes #102:
- removes everything that is related to WebSockets
- bump the vaultwarden version to 1.31.0
- bump the chart minor version
=> chore: bump to 1.31.0

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/templates/secrets.yaml, charts/vaultwarden/values.yaml
Enable use of existing secrets for bitwarden installation id and key for push notifications.
Both, installation key and id, shouldn't be made public when deploying via gitops. This enables using a seperate (encrypted) secret for defining installation id and key.
Based on the smtp configuration
New section in values.yaml looks the following:
```
pushNotifications: 
existingSecret: ""
installationId: 
value: ""
existingSecretKey: ""
installationKey:
value: ""
existingSecretKey: ""
relayUri: "https://push.bitwarden.com"
identityUri: "https://identity.bitwarden.com"
```
It is possible to specify a string value in installationId.value or installationKey.value.
My implementation contains a breaking change due to the indroduction of installationId.value and installationKey.value instead of …
=> Push Notifications existing secret

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/values.yaml
With the introduction of the push notification keys in PR #106, the check for value `pushNotifications` started to return true by default, which breaks installations that do not have notifications configured.
To fix this, we're introducing a new flag `pushNotifications.enabled` to set this feature on, `false` by default.
When updating to this version, please add the flag to your values file:
```yaml
...
pushNotifications:
enabled: true
...
=> fix: add flag to enable notifications service

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/service.yaml
fixes #93 
before:
```
$ helm template release ./vaultwarden
[snip]
apiVersion: v1
kind: Service
metadata:
name: release-vaultwarden
namespace: default
labels:
app.kubernetes.io/component: vaultwarden
helm.sh/chart: vaultwarden-0.23.0
app.kubernetes.io/name: vaultwarden
app.kubernetes.io/instance: release
app.kubernetes.io/version: "1.30.3"
app.kubernetes.io/managed-by: Helm
spec:
type: "ClusterIP"
selector:
app.kubernetes.io/component: vaultwarden
ports:
- name: "http"
port: 80
protocol: TCP
targetPort: 8080
- name: "websocket"
port: 3012
protocol: TCP
targetPort: 3012
ipFamilyPolicy: SingleStack
[snip]
```
after:
```
$ helm template release ./vaultwarden
[snip]
kind: Service
metadata:
name: release-vaultwarden
namespace: default
labels:
app.kubernetes.io/component: vaultwarden …
```
=> service: use selectorLabels helper

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/templates/ingress.yaml, charts/vaultwarden/values.yaml
Our cluster does not allow snippet annotations by default and changing the configuration would be complicated.
But the snippet is not actually needed, since the same thing can be achieve using a config map and the custom-headers annotation.
=> feat: Replace nginx snippet annotation with custom header annotation

Makefile, charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/ci/test-values.yaml, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/templates/secrets.yaml, charts/vaultwarden/values.yaml
=> feat: yubico and duo as secretkeys

charts/vaultwarden/Chart.yaml, charts/vaultwarden/values.yaml
- Bumped Vaultwarden app version to 1.32.1 in the Helm chart to ensure compatibility with the latest features and fixes.
- Updated Helm chart version to 0.29.1 to reflect the changes in the app version and maintain version consistency.
The changes have been tested, and the functionality works as expected with the updated Vaultwarden version. No issues were encountered during deployment or runtime.
Please review and let me know if any adjustments are needed!
=> bump Vaultwarden app version to 1.32.1, Chart version update to 0.29.1

charts/vaultwarden/Chart.yaml, charts/vaultwarden/values.yaml
This pull request includes the following changes:
- Bumped Vaultwarden app version to 1.32.2 in the Helm chart to ensure compatibility with the latest features and fixes.
- Updated Helm chart version to 0.29.2 to reflect the changes in the app version and maintain version consistency.
Testing:
The changes have been tested, and the functionality works as expected with the updated Vaultwarden version. No issues were encountered during deployment or runtime.
Please review and let me know if any adjustments are needed!
=> chore: Bump Vaultwarden App version to 1.32.2

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/values.yaml
Hi,
I just deployed Vaultwarden using chart, I configured Vaultwarden to run on non root path (/vaultwarden), this however causes the pod to be restarted since the chart deployment probe checks only /alive which needs to be /vaultwarden/alive in my case.
This chart fixes that problem and allows the probe URL to be set.
=> Add probe override support

charts/vaultwarden/Chart.yaml, charts/vaultwarden/values.yaml
Release announcement: https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.5
=> chore: Update default image to 1.32.5

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_helpers.tpl, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/templates/_pvcSpec.tpl, charts/vaultwarden/templates/configmap.yaml, charts/vaultwarden/templates/deployment.yaml, charts/vaultwarden/values.yaml
Added support for existing PVC's.  This is a more up to date version of a lot of the enhancements made in the following PR, but recreated for a more fresh PR https://github.com/guerzon/vaultwarden/pull/19 .
This is a breaking change as the `data` and `attachment` objects have been moved under a `storage` key.
=> Adding Support For Existing PVC

charts/vaultwarden/Chart.yaml, charts/vaultwarden/templates/deployment.yaml
Resolves #135 
Confirmed the following via tests:
- Inclusion of `storage.existingVolumeClaim` does not create a `volume` key in the deployment
- Omitting `storage.existingVolumeClaim` and creating either/or/both of `storage.data / storage.attachments` creates a single `volume` key with children for each
(dont judge my test keys lol as i had to spoof the volumeClaim names to avoid errors with `includes` in my test)
=> Fix issue where pvc range produced multiple volume keys

charts/vaultwarden/Chart.yaml, charts/vaultwarden/README.md, charts/vaultwarden/templates/_podSpec.tpl, charts/vaultwarden/values.yaml
I am currently using this helm chart in combination with the image from [Timshel/OIDCWarden](https://github.com/Timshel/OIDCWarden).
However, since that image requires that several environment variables, some of which are confidential like `SSO_CLIENT_SECRET`, are set, I would like to outsource them so that they are not in plain text in the values file.
As long as #153 has not yet been merged, this one provides a solution
=> Add extra env vars from ConfigMap or Secret
