Chart.yaml
templates/configmap.yaml
templates/statefulset.yaml
values.yaml

Adds logging variables so you can customize logging (including using said logs for fail2ban).
I think this adds some important customization without being needlessly complex, but I'm open to suggestions, especially regarding default values

Added logging variables

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

Hello!
I would like to help with developing this helm chart and added some useful features like:
- Checksums in statefulset to recreate container when some configurations are changed
- Additional configurations via nodeselector, tolerations, affinity

Checksums for configs and Nodeselector, affinity, and tolerations

---

Chart.yaml
README.md
templates/statefulset.yaml
values.yaml

Hello, just a feature to configure pod annotations and labels. I need some annotations to control my mutating admission webhook to inject backup and restore containers.

feat: pod annotations & labels

---

.gitignore
CONTRIBUTING.md
generate-readme.sh

Hi, a handy script to generate the readme.

chore: script to generate the readme.md

---

cr.yaml

This will generate release notes using GitHub's automation: https://docs.github.com/en/rest/releases/releases
Read more here: https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages
Alternatively, you change your github action to pass this in as a parameter like this:
```yaml
- name: Run chart-releaser
id: helm-release
uses: helm/chart-releaser-action@v1.5.0
env:
CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
CR_GENERATE_RELEASE_NOTES: true
```

Update cr.yaml - autogenerate release notes

---

charts/vaultwarden/templates/configmap.yaml

This was causing this section to be rendered even if conditional was not met.

Update configmap.yaml - fix quoting of conditional

---

.github/workflows/ci-helm-lint-test.yml

This would just make sure that each PR that comes through, runs against a basic check to see if the Chart will install as per the instructions in the README.md.

Create ci-helm-lint-test.yml - adds a linter that runs on all new PRs

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/statefulset.yaml

feat: add podAnnotations on StatefulSet

---

.github/FUNDING.yml
CONTRIBUTING.md
Makefile
README.md
charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/templates/configmap.yaml
charts/vaultwarden/templates/secrets.yaml
charts/vaultwarden/templates/statefulset.yaml
charts/vaultwarden/values.yaml
generate-readme.sh

Quite a list of features. Sunday well-spent (?)
- allow disabling the admin token
- minor fix to writing initContainers in template
- update example for signupDomains
- add support for push notifications
- rework storage variable and add support for custom attachments dir
- Makefile for testing
- fix logging configuration
- use alpine image
- move resource config to values.yml
- add readiness probe
- add funding button for repo

feat: multiple features

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/templates/statefulset.yaml
charts/vaultwarden/values.yaml

fix: sts annotations

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/templates/configmap.yaml
charts/vaultwarden/values.yaml

This release includes the following:
- Update the application version to `1.30.3`
- Add support for multiple features
- Reorganize values to follow vaultwarden's environment vars template

feat: update app, add more options, reorg docs

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/_podSpec.tpl

Recently i added feature extraSecrets, but I found a stupid bug. Can you review it and merge it please @guerzon :pray:

Fixed extraSecrets

---

.github/FUNDING.yml
charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/_pvcSpec.tpl
charts/vaultwarden/templates/pvc.yaml
charts/vaultwarden/values.yaml

feat: volume improvements

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/configmap.yaml
charts/vaultwarden/values.yaml

fix: make customHeadersConfigMap optional

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/ingress.yaml

Earlier fix to #111 was incomplete, adding this fix to the ingress resource.

fix: incomplete fix, additional

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/values.yaml

- updates application version to [1.32.0](https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.0)
- fixes #115

update application to 1.32.0

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/ci/test-values.yaml
charts/vaultwarden/templates/_podSpec.tpl
charts/vaultwarden/values.yaml

feat: make enableServiceLinks configurable

---

.gitignore
charts/vaultwarden/Chart.yaml
charts/vaultwarden/README.md
charts/vaultwarden/ci/test-values.yaml
charts/vaultwarden/templates/_podSpec.tpl
charts/vaultwarden/values.yaml
demo.yaml

feat: imagePullSecrets support

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/values.yaml

Release announcement: https://github.com/dani-garcia/vaultwarden/releases/tag/1.32.7

chore: Update default image to 1.32.7

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/values.yaml

Release announcement: https://github.com/dani-garcia/vaultwarden/releases/tag/1.33.0

Update default image to 1.33.0

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/values.yaml

VaultWarden 1.33.2 has been released.

Bump to 1.33.2 Vaultwarden

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/ingress.yaml

fix: remove keepalive annotation

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/poddisruptionbudget.yaml

fix: selector.matchLabels for PDB

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/templates/ingress.yaml

chore: cleanup unused annotations

---

charts/vaultwarden/Chart.yaml
charts/vaultwarden/values.yaml

fix: adjust default image tag to match appVersion
